name: Print Context

on:
  push:
    

jobs:

  build:
    name: Print Context
    runs-on: ubuntu-latest
    steps:

    - name: Check out code 
      uses: actions/checkout@v2

    - name: Print GitHub context
      if: github.actor == "danielinclouds"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"